name: Lint and Test

on:
  push:
    branches: 
      - main
      

  pull_request:
    branches: 
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Black (formatting)
      run: |
        black --check .

    - name: Run isort (imports)
      run: |
        isort --check-only .

    - name: Run flake8 (style)
      run: |
        flake8 --max-line-length=88 --exclude=venv .

    - name: Run pylint (quality)
      run: |
        pylint gilded_rose.py

    - name: Run mypy (type checking)
      run: |
        mypy gilded_rose.py

    - name: Run tests
      run: |
        python -m unittest discover -s tests
